//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishingHotspotsDBEntities : DbContext
    {
        public FishingHotspotsDBEntities()
            : base("name=FishingHotspotsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FishCaughtTbl> FishCaughtTbls { get; set; }
        public virtual DbSet<FishSpeciesTbl> FishSpeciesTbls { get; set; }
        public virtual DbSet<FishTypeTbl> FishTypeTbls { get; set; }
        public virtual DbSet<LakesTbl> LakesTbls { get; set; }
        public virtual DbSet<NewsTbl> NewsTbls { get; set; }
        public virtual DbSet<RatingsTbl> RatingsTbls { get; set; }
        public virtual DbSet<RegionsTbl> RegionsTbls { get; set; }
        public virtual DbSet<ReviewsTbl> ReviewsTbls { get; set; }
        public virtual DbSet<RiversTbl> RiversTbls { get; set; }
        public virtual DbSet<UserRolesTbl> UserRolesTbls { get; set; }
        public virtual DbSet<UsersTbl> UsersTbls { get; set; }
    }
}
