//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishCaughtTbl
    {
        public int Id { get; set; }
        public Nullable<double> Weight { get; set; }
        public string Method { get; set; }
        public byte FishSpecies { get; set; }
        public int Review { get; set; }
    
        public virtual FishSpeciesTbl FishSpeciesTbl { get; set; }
        public virtual ReviewsTbl ReviewsTbl { get; set; }
    }
}
