//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FishTypeTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FishTypeTbl()
        {
            this.FishSpeciesTbls = new HashSet<FishSpeciesTbl>();
            this.ReviewsTbls = new HashSet<ReviewsTbl>();
        }
    
        public byte id { get; set; }
        public string FishingTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FishSpeciesTbl> FishSpeciesTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewsTbl> ReviewsTbls { get; set; }
    }
}
