//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishingHotspotsDBEntities : DbContext
    {
        public FishingHotspotsDBEntities()
            : base("name=FishingHotspotsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FishCaughtTbl> FishCaughtTbl { get; set; }
        public virtual DbSet<FishSpeciesTbl> FishSpeciesTbl { get; set; }
        public virtual DbSet<FishTypeTbl> FishTypeTbl { get; set; }
        public virtual DbSet<LakesTbl> LakesTbl { get; set; }
        public virtual DbSet<NewsTbl> NewsTbl { get; set; }
        public virtual DbSet<RatingsTbl> RatingsTbl { get; set; }
        public virtual DbSet<RegionsTbl> RegionsTbl { get; set; }
        public virtual DbSet<ReviewsTbl> ReviewsTbl { get; set; }
        public virtual DbSet<RiversTbl> RiversTbl { get; set; }
        public virtual DbSet<UserRolesTbl> UserRolesTbl { get; set; }
        public virtual DbSet<UsersTbl> UsersTbl { get; set; }
    }
}
