//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewsTbl()
        {
            this.FishCaughtTbls = new HashSet<FishCaughtTbl>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public string ReviewText { get; set; }
        public byte[] Photo { get; set; }
        public byte FishingType { get; set; }
        public int Region { get; set; }
        public Nullable<int> Rating { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FishCaughtTbl> FishCaughtTbls { get; set; }
        public virtual FishTypeTbl FishTypeTbl { get; set; }
        public virtual RatingsTbl RatingsTbl { get; set; }
        public virtual RegionsTbl RegionsTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
    }
}
