//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingHotspots.FishingHotspotsEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiversTbl
    {
        public int Id { get; set; }
        public string RiverName { get; set; }
        public int Region { get; set; }
    
        public virtual RegionsTbl RegionsTbl { get; set; }
    }
}
